### ISSUE TITLE
No way to get client's IP address

### ISSUE THREAD

**Issue by Undefine-Unity** [tom-weiland/RiptideNetworking#15]
I think there should be a field in the IConnectionInfo with the player's IP address, it could be useful for some custom debug messages.

**Comment by tom-weiland** [comment]
`IConnectionInfo` needs to be transport-agnostic, meaning an IP field isn't an option as not all transports will use IPs (the [Steam transport](https://github.com/tom-weiland/RiptideSteamTransport) being a prime example as it manages connections through Steam IDs, not IPs).

If you're using the default transport and you need to access client IPs, `RudpConnection` [has an IP field](https://github.com/tom-weiland/RiptideNetworking/blob/1b684a78897e0b4bc054d75681184e3d6f48b6d7/RiptideNetworking/RiptideNetworking/Transports/RudpTransport/RudpConnection.cs#L29), so you could just cast the `IConnectionInfo` object to that:

```
((RudpConnection)theIConnectionInfoObject).RemoteEndPoint
```
