### ISSUE TITLE
[Suggestion] Allow server to have unlimited client slots

### ISSUE THREAD

**Issue by ClonkAndre** [tom-weiland/RiptideNetworking#2]
It would be a cool feature if you could set the **maxClientCount** parameter in the **Server.Start** method to like **0** and this would mean that the server doesn't have a max client limitation.

This would be pretty useful in some applications. Like if you dont want the server to be a game server.

**Comment by tom-weiland** [comment]
Well due to the fact that client IDs are a ushort, there's going to be a limit of 65535 clients anyways, but you'll almost certainly hit hardware and bandwidth limitations _long_ before you reach that.

What are you trying to use this for that requires (and could theoretically handle) unlimited clients?

**Comment by ClonkAndre** [comment]
I'm trying to write a master server where users can register their own server to. And the master server lists all the servers currently registered and gathers their ping and some informations. So i think a master server shouldn't have any max clients limitations i guess, because the master server should obviously list all the servers available.

I'm not sure if this is the right way to create a master server tho. Do you think this is the right approach?

**Comment by tom-weiland** [comment]
If you just want a server list, you should probably use a web server or something for that. No need for fast UDP transfer if that's all you're trying to do.

Also, you'd probably end up with multiple master servers for various regions, as listing _every_ server in the world for users in completely different regions wouldn't make much sense. If you need more than 65k connections at once (assuming you have the resources for it, which is unlikely in more general game-server use cases), you could also create a second instance of the Server class and use that to listen on a separate port.

**Comment by ClonkAndre** [comment]
Yeah you're right. I'll see what i can do about that. Thanks for the idea with multiple master servers for various regions, i haven't thought about that to be honest.
