### ISSUE TITLE
Adding a enum constructor for the messageHandlerAttribute

### ISSUE THREAD

**Issue by Eleocraft** [tom-weiland/RiptideNetworking#21]
Since you added an overflow method to the Message.Create function in the last update, you could just do the same for the constructor in the messageHandlerAttribute. that way you could directly insert enums.

**Comment by tom-weiland** [comment]
I actually tried that initially, but unfortunately it's not possible. Attribute constructors have a limited list of [acceptable parameter types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#2124-attribute-parameter-types).

They can take in enum types, but not the actual `Enum` class :/

**Comment by Eleocraft** [comment]
Oh, good to know. Fortunately in this case its really not a big deal.
