### ISSUE TITLE
Support WebGL with WebSockets

### ISSUE THREAD

**Issue by NothingMuch123** [tom-weiland/RiptideNetworking#24]
Are there any roadmaps on supporting WebGL builds with websockets?

**Comment by ERmilburn02** [comment]
You can always build your own transport using WebSockets.

**Comment by tom-weiland** [comment]
> Are there any roadmaps on supporting WebGL builds with websockets?

Nope. It's something I might look into in the future, but definitely not before the Riptide tutorial series is finished, and I have no idea when that'll be. I also need to finish up the Steam transport at some point, so I've got plenty of things to do before working on WebGL support...

**Comment by NothingMuch123** [comment]
Appreciate the responses. Guess I'll have to build my own transport then.
