### ISSUE TITLE
Connecting to non-server devices

### ISSUE THREAD

**Issue by DeexCoding** [tom-weiland/RiptideNetworking#27]
Are there any consequences to connectiong to a device that hasn't got anything to do with my app? Eg. if I would connect to my TV through code would my device show up on it?

**Comment by tom-weiland** [comment]
What do you mean "would your device show up on it"? Connecting to devices that aren't listening for your app's activity could lead to crashes if you have nothing in place to handle packets containing unexpected data. Other than that I'm not really aware of any obvious consequences, but you'd have to try it...
