### ISSUE TITLE
Error adding package to unity.

### ISSUE THREAD

**Issue by Pinball3D** [tom-weiland/RiptideNetworking#28]
I opened the package manager, and then clicked + > Add from git url... and then pasted this: https://github.com/tom-weiland/RiptideNetworking.git?path=/UnityPackage It then gives me this error: "[Package Manager Window] Error adding package: https://github.com/tom-weiland/RiptideNetworking.git?path=/UnityPackage." please help

**Comment by tom-weiland** [comment]
Do you have git installed on your computer? I believe it's required for the Unity Package Manager to be able to install packages via git.

If that doesn't help, you may want to ask on the Unity forums. Considering I'm able to install the package with that url and no one else has reported problems, this seems to be more of a Unity issue on your end than anything else.
