### ISSUE TITLE
Scan Local Network for Active Servers

### ISSUE THREAD

**Issue by NoCultist** [tom-weiland/RiptideNetworking#31]
I could really use an option to scan the local network for servers listening on the selected port, or at least an option to ping servers by IP and port, without the long timeout that comes with trying to connect to a server not knowing if it's even online...

Not sure if I'm clear enough but I'm trying to make a game with LAN/WLAN multiplayer that has autodiscovery of available hosts. 
If it's possible to do that as is I'd be extremely grateful for any help.

**Comment by tom-weiland** [comment]
Sounds like you're looking for the [LanDiscovery](https://github.com/tom-weiland/RiptideNetworking/blob/main/RiptideNetworking/RiptideNetworking/Utils/LanDiscovery.cs) class 😉

For a short explanation on setting it up, take a look at [this](https://github.com/tom-weiland/RiptideNetworking/issues/29#issuecomment-1089283964).
