### ISSUE TITLE
A way to deny connections on the server

### ISSUE THREAD

**Issue by MrCelsius88** [tom-weiland/RiptideNetworking#32]
I don’t know if this is already a feature, but I was wondering if there was a way for the server to deny incoming connections. For example everyone joins the server in the “lobby” and then when the game starts nobody can join at this point until the game finishes like in among us lol. So the server will keep the clients that connected before the game starts but will deny any new incoming connections.

**Comment by tom-weiland** [comment]
Currently all you can do is immediately disconnect the person trying to join late (using the server's `DisconnectClient` method), but I may add a way to refuse connections so the ClientConnected event never fires.

**Comment by tom-weiland** [comment]
Reopening this as it's something I do want to implement.
