### ISSUE TITLE
How can I disable the messages that are sent to all connected clients.

### ISSUE THREAD

**Issue by irocker04** [tom-weiland/RiptideNetworking#33]
The problem is the following. I want to make a server where everyone connects, but no information should be automatically send to everyone. I do not need my clients to know about all connected and disconnected clients. how can I turn off autosending these messages.

**Comment by tom-weiland** [comment]
You can't—auto-sending the connect/disconnect messages incurs virtually no performance/bandwidth cost, so why do you need to disable them? Just don't do anything with the events if you don't want to.
