### ISSUE TITLE
Please add a thing that works like a chat room, where players can join and chat!

### ISSUE THREAD

**Issue by mohanpalsingh** [tom-weiland/RiptideNetworking#34]
Ok, I started using Riptide and noticed that this was missing, we can use the chat rooms for online chatting for players, I mean just make a class that handles `SendChatMessage(string message)`, `onChatMessageRecived(string messageRecived)`, `onJoinChat(),` `onLeaveChat()`. This will be very useful for users please. Overall this is the best multiplayer solution I ever saw, so I am gonna use **this** for my games!

**Comment by MrCelsius88** [comment]
This sounds like something that you would code yourself, riptide gives you the tools to make this and now it’s up to you to put them to use ;). I made a chat system myself not too long ago and it is fairly simple. You can structure it on just connecting to the server and handling chat messages the same way you would handle other messages.

**Comment by tom-weiland** [comment]
But why? That's something that Riptide gives you the tools to do, but it really doesn't belong in Riptide's core. If you want to let players send chat messages, just add a method that creates a message, adds the chat string and sends it.
