### ISSUE TITLE
Any plans for future?

### ISSUE THREAD

**Issue by Maclay74** [tom-weiland/RiptideNetworking#35]
Probably it was already discussed on your Youtube channel, but still.

Do you have any roadmap for the library? 
I understand that you want to keep it as basic as possible, but there are some features that might be handy for most of projects.

**Comment by tom-weiland** [comment]
There's currently no roadmap, no. I have a short list of a few things to fix/change/add, but there's nothing super major in there. If you've got suggestions, feel free to let me know and I'll consider them though.

I'm thinking about potentially building some high level stuff on top of Riptide, but at this point I'm not sure if that'll actually happen...
