### ISSUE TITLE
found that when Attempts to send the message，it is error，

### ISSUE THREAD

**Issue by 664028812** [tom-weiland/RiptideNetworking#38]
The client is originally logged in, but sendattempts > = maxsendattempts are often used in circular detection. The server directly causes an error. What should be the problem with the thread?

   /// <summary>Attempts to send the message.</summary>
        internal void TrySend()
        {
            if (sendAttempts >= maxSendAttempts)
            {
                // Send attempts exceeds max send attempts, so give up
                //发送尝试次数超过最大发送尝试次数，所以放弃
                if (RiptideLogger.IsWarningLoggingEnabled)
                {
                    HeaderType headerType = (HeaderType)data[0];
                    if (headerType == HeaderType.reliable)
                    {
#if BIG_ENDIAN
                        ushort messageId = (ushort)(data[4] | (data[3] << 8));
#else
                        ushort messageId = (ushort)(data[3] | (data[4] << 8));
#endif
                        RiptideLogger.Log(LogType.warning, peer.Listener.LogName, $"No ack received for {headerType} message (ID: {messageId}) after {sendAttempts} attempt(s), delivery may have failed!");
                    }
                    else
                        RiptideLogger.Log(LogType.warning, peer.Listener.LogName, $"No ack received for internal {headerType} message after {sendAttempts} attempt(s), delivery may have failed!");
                }

                Clear();
                return;
            }

**Comment by tom-weiland** [comment]
I'm confused—is this meant to be a response to issue #37? If so, why did you create a new issue?

Either way, I'm not even sure what you're trying to say...
> The server directly causes an error.

What error?
> What should be the problem with the thread?

What problem? What thread? I won't be able to help much if you can't clarify what the actual issue is that you're experiencing.

**Comment by tom-weiland** [comment]
Closing this due to a lack of information and no response from @664028812.
