### ISSUE TITLE
Event handlers not working & messages are not sending/receiving

### ISSUE THREAD

**Issue by ameel** [tom-weiland/RiptideNetworking#47]
Hi,

I am using latest release [v1.2.0]. I have the basic code below for client:

> using System;
> using System.Collections.Generic;
> using System.Linq;
> using System.Text;
> using System.Threading.Tasks;
> using RiptideNetworking;
> using RiptideNetworking.Utils;
> public enum ServerToClientId : ushort
> {
>     playerSpawned = 1,
> }
> public enum ClientToServerId : ushort
> {
>     name = 1,
> }
> internal class NetworkManager
> {
>     private static NetworkManager _singleton;
>     public static NetworkManager Singleton
>     {
>         get => _singleton;
>         set
>         {
>             if (_singleton == null)
>                 _singleton = value;
>             else if (_singleton != value)
>             {
>                 Console.WriteLine($"{nameof(NetworkManager)} instance already exists, destroying duplicate!");
>             Console.WriteLine(value);
>             }
>         }
>     }
>     public Client Client { get; set; }
>     private string ip = "127.0.0.1";
>     private ushort port = 23787;
> private void Initialize()
> {
>     Singleton = this;
> }
>     public void Start()
>     {
>         RiptideLogger.Initialize(Console.WriteLine, Console.WriteLine, Console.WriteLine, Console.WriteLine, false);
>         Client = new Client();
>         Client.Connected += DidConnect;
>         Client.ConnectionFailed += FailedToConnect;
>         Client.ClientDisconnected += PlayerLeft;
>         Client.Disconnected += DidDisconnect;
>         Client.ClientConnected += DidConnect;
>     }
>     private void FixedUpdate()
>     {
>         Client.Tick();
>     }
>     private void OnApplicationQuit()
>     {
>         Client.Disconnect();
>     }
>     public void Connect()
>     {
>         Client.Connect($"{ip}:{port}");
>     }
>     private void DidConnect(object sender, EventArgs e)
>     {
>         //UIManager.Singleton.SendName();
>         Console.WriteLine("@DidConnect");
>     }
>     private void FailedToConnect(object sender, EventArgs e)
>     {
>         Console.WriteLine("@FailedToConnect");
>     }
>     private void PlayerLeft(object sender, ClientDisconnectedEventArgs e)
>     {
>         Console.WriteLine("@PlayedLeft");
>     }
>     private void DidDisconnect(object sender, EventArgs e)
>     {
>         Console.WriteLine("@DidDisconnect");
>     }
> }
> 

None of the event handlers are working:
>         Client.Connected += DidConnect;
>         Client.ConnectionFailed += FailedToConnect;
>         Client.ClientDisconnected += PlayerLeft;
>         Client.Disconnected += DidDisconnect;
>         Client.ClientConnected += DidConnect;

I am not sure if I am doring anything wrong. Please help.

**Comment by manel-graca** [comment]
@ERmilburn02 is totally right! 
You are subscribing to all those events in Start() method, that is a MonoBehaviour method. 
If your class does not inherit from MonoBehaviour, the Start(), Update()... etc. will not be called how it "normally" should.

Are you calling Start() from another script?

**Comment by tom-weiland** [comment]
@ameel as the others have mentioned, make sure your `NetworkManager` inherits from `Monobehaviour` and that it's attached to a game object, or that you're manually calling all the methods which Unity would normally invoke for you. If you could confirm whether or not that solves the problem, that'd be great :)

Also, in the future you should use code blocks instead of quotes to format your code—that way the indentation will be retained and it's much easier to read.

**Comment by ERmilburn02** [comment]
> Also, in the future you should use code blocks instead of quotes to format your code—that way the indentation will be retained and it's much easier to read.
Yes, it really does help with code readability.

**Comment by ERmilburn02** [comment]
> Also, in the future you should use code blocks instead of quotes to format your code—that way the indentation will be retained and it's much easier to read.
Yes, it really does help with code readability.

**Comment by ameel** [comment]
Hi All,

Thank you for the responses. I was trying to setup console apps, not in unity, which is wh MonoBehaviour was not attached. I also called Start() manually from my program.

Reviewing the other example for MonoGame, it looks like Client.Tick() needs to sit in a loop as FixedUpdate() does not get called.

Thanks!

**Comment by ERmilburn02** [comment]
If they're console apps, you should reference the console Demos

https://github.com/tom-weiland/RiptideNetworking/tree/main/Demos%2FConsole
