### ISSUE TITLE
Client.ClientDisconnected and Client.Disconnected not working

### ISSUE THREAD

**Issue by ameel** [tom-weiland/RiptideNetworking#49]
Hi,

I have the following code in my Start():
`Client.Disconnected += DidDisconnect;
Client.ClientDisconnected += DidDisconnect;
Client.ConnectionFailed += FailedToConnect;`

and

`private void DidDisconnect(object sender, EventArgs e){
        Debug.Log("@DidDisconnect");
}`

`Client.ClientConnected += DidConnect;` works

When server is closed, and client is disconnected, unity debug shows:
> (CLIENT): Disconnected from server (initiated remotely).
> UnityEngine.Debug:Log (object)
> RiptideNetworking.Utils.RiptideLogger:Log (RiptideNetworking.Utils.LogType,string,string)
> RiptideNetworking.Transports.RudpTransport.RudpClient:OnDisconnected ()
> RiptideNetworking.Transports.RudpTransport.RudpClient:Heartbeat ()
> RiptideNetworking.Transports.RudpTransport.RudpClient:<Connect>b__54_0 (object)
> System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

However, DidDisconnect is not called at all. Any insight/ideas?

Thank you!

**Comment by tom-weiland** [comment]
Are you calling the client's `Tick` method in `FixedUpdate`? Without that, events won't be invoked.

**Comment by ameel** [comment]
@tom-weiland Yes, that was the issue. I had a checkin FixedUpdate but I forgot to update it and that stopped working.

Thanks for pointing it out!
