### ISSUE TITLE
Apple review team can not connect with the server

### ISSUE THREAD

**Issue by Bilnord** [tom-weiland/RiptideNetworking#57]
Publishing game with RiptideNetworking for AppStore Connect review will be always rejected because their team can not connect with the server (in my case to dedicated server and the connection is necessary to use the game). My dedicated server is correctly configured including server firewall. Reffering to conversations with other developers it looks like their review center firewall deny UDP. The only solution to this problem in my opinion is to make TCP transport for Riptide as a fallback server to successfuly publish the game on AppStore.

**Comment by ERmilburn02** [comment]
Riptide is designed to be easy to add new transports to, have you considered trying to make the transport yourself and submitting a pull request?
