### ISSUE TITLE
Message contains insufficient unread bytes (0) to read type 'ushort', returning 0!

### ISSUE THREAD

**Issue by PathPDX** [tom-weiland/RiptideNetworking#62]
It works fine when sending from client to server, but when the server responds I get this on the client...

No client-side handler method found for message ID 0!

... and this on the server...

Message contains insufficient unread bytes (0) to read type 'ushort', returning 0!

Code is from scratch and this here seems pretty straight forward...

public static void Send(ushort clientID, ushort command, string value) => Server.Send(Message.Create(MessageSendMode.reliable, command).AddString(value), clientID);

**Comment by PathPDX** [comment]
I doubt this is related, but the server is also completely hanging when it gets to "Reload Script Assemblies".

**Comment by tom-weiland** [comment]
Could you post all the code (from both sides) that's creating, sending and handling the messages in question?

> No client-side handler method found for message ID 0!

This is very odd—do your message ID enums start at 1 like in the tutorials & demos, or did you start them at 0/not set a starting value? If it's the former, that would imply that the data it's using to determine the message ID is messed up for some reason...

Can you consistently reproduce this or is its occurrence somewhat irregular?

**Comment by PathPDX** [comment]
I don't really understand the purpose of enums, I'm afraid. Do they have to be enums? I did have the numbers starting at 0, but sending 0 to the server worked. Sending any number back failed, 0 or 1. This is the client...

using RiptideNetworking;
using RiptideNetworking.Utils;
using System;
using UnityEngine;
/// <summary>Commands the client can send to the server.</summary>
public class CCom
{
    public const ushort Login = 1;
}
/// <summary>Commands the server can send to the client.</summary>
public class SCom
{
    public const ushort LoginError = 1;
    public const ushort LoadScreen = 2;
}
public class OClient : MonoBehaviour
{
    public static OClient Instance;
    public static Client Client;
    public static ushort Port = 6000;
    public static string IP = "127.0.0.1";
    public void Start()
    {
        Instance = this;
        RiptideLogger.Initialize(Debug.Log, Debug.Log, Debug.LogWarning, Debug.LogError, false);
        Client = new Client();
        Client.Connected += DidConnect;
        Client.Disconnected += DidDisconnect;
        Client.ConnectionFailed += FailedToConnect;
    }
    public void Update()
    {
        Client?.Tick();
    }
    public void OnApplicationQuit()
    {
        Disconnect();
    }
    public void DidConnect(object sender, EventArgs e)
    {
        Game.UI.SendLogin();
    }
    static void FailedToConnect(object sender, EventArgs e)
    {
        Game.UI.BackToMain();
        Game.UI.errorText.text = "Failed to connect.";
    }
    static void DidDisconnect(object sender, EventArgs e)
    {
        Game.UI.BackToMain();
    }
    public static void Disconnect()
    {
        Client.Disconnect();
    }
    public static void Connect()
    {
        Client.Connect($"{IP}:{Port}");
    }
    public static void Send(Message message)
    {
        Client.Send(message);
    }
    [MessageHandler(SCom.LoginError)]
    public static void LoginError(ushort cid, Message message)
    {
        Game.UI.errorText.text = message.GetString();
    }
}

Server....

using RiptideNetworking;
using RiptideNetworking.Utils;
using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>Commands the client can send to the server.</summary>
public class CCom
{
    public const ushort Login = 1;
}
/// <summary>Commands the server can send to the client.</summary>
public class SCom
{
    public const ushort LoginError = 1;
    public const ushort LoadScreen = 2;
}

public class OServer : MonoBehaviour
{
    public static OServer Instance;
    public static Server Server;
    public static Dictionary<ushort, Player> Connected = new Dictionary<ushort, Player>();
    [SerializeField] public static ushort Port;
    [SerializeField] public static string IP;
    [SerializeField] public static ushort MaxClients;
    public static void Send(ushort clientID, ushort command, string value) => Server.Send(Message.Create(MessageSendMode.reliable, command).AddString(value), clientID);
    public static void Tick() => Server.Tick();
    public static void Stop() => Server.Stop();
    public void Start()
    {
        Instance = this;
        MaxClients = 32;
        RiptideLogger.Initialize(Debug.Log, Debug.Log, Debug.LogWarning, Debug.LogError, false);
        Server = new Server();
        Game.BaseDirectory = AppDomain.CurrentDomain.BaseDirectory;
        if (Game.BaseDirectory == "C:\\Program Files\\Unity\\Hub\\Editor\\2021.3.7f1\\Editor")
        {
            Game.SUPER_DEBUG = Game.DevServer = true;
            Game.LiveOffline = true;
            IP = "127.0.0.1";
            Port = 6000;
        }
        else
        {
            // Blah blah...
        }
        Game.Startup();
        Server.Start(Port, MaxClients);
    }

    [MessageHandler(CCom.Login)]
    public static void Login(ushort fromClientID, Message message)
    {
        string name = message.GetString();
        string error = Database.ValidatePlayer(message.GetString(), message.GetString());
        if (error == "")
        {
            Player p = Player.Get(name, "");
            if (p == null)
                Send(fromClientID, SCom.LoginError, "Player banned.");
            else
                p.SignIn(fromClientID);
        }
        else
            Send(fromClientID, SCom.LoginError, error);
    }
}

**Comment by PathPDX** [comment]
`using RiptideNetworking;
using RiptideNetworking.Utils;
using System;
using UnityEngine;
/// <summary>Commands the client can send to the server.</summary>
public class CCom
{
    public const ushort Login = 1;
}
/// <summary>Commands the server can send to the client.</summary>
public class SCom
{
    public const ushort LoginError = 1;
    public const ushort LoadScreen = 2;
}
public class OClient : MonoBehaviour
{
    public static OClient Instance;
    public static Client Client;
    public static ushort Port = 6000;
    public static string IP = "127.0.0.1";
    public void Start()
    {
        Instance = this;
        RiptideLogger.Initialize(Debug.Log, Debug.Log, Debug.LogWarning, Debug.LogError, false);
        Client = new Client();
        Client.Connected += DidConnect;
        Client.Disconnected += DidDisconnect;
        Client.ConnectionFailed += FailedToConnect;
    }
    public void Update()
    {
        Client?.Tick();
    }
    public void OnApplicationQuit()
    {
        Disconnect();
    }
    public void DidConnect(object sender, EventArgs e)
    {
        Game.UI.SendLogin();
    }
    static void FailedToConnect(object sender, EventArgs e)
    {
        Game.UI.BackToMain();
        Game.UI.errorText.text = "Failed to connect.";
    }
    static void DidDisconnect(object sender, EventArgs e)
    {
        Game.UI.BackToMain();
    }
    public static void Disconnect()
    {
        Client.Disconnect();
    }
    public static void Connect()
    {
        Client.Connect($"{IP}:{Port}");
    }
    public static void Send(Message message)
    {
        Client.Send(message);
    }
    [MessageHandler(SCom.LoginError)]
    public static void LoginError(ushort cid, Message message)
    {
        Game.UI.errorText.text = message.GetString();
    }
}
`

Server....

`using RiptideNetworking;
using RiptideNetworking.Utils;
using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>Commands the client can send to the server.</summary>
public class CCom
{
    public const ushort Login = 1;
}
/// <summary>Commands the server can send to the client.</summary>
public class SCom
{
    public const ushort LoginError = 1;
    public const ushort LoadScreen = 2;
}

public class OServer : MonoBehaviour
{
    public static OServer Instance;
    public static Server Server;
    public static Dictionary<ushort, Player> Connected = new Dictionary<ushort, Player>();
    [SerializeField] public static ushort Port;
    [SerializeField] public static string IP;
    [SerializeField] public static ushort MaxClients;
    public static void Send(ushort clientID, ushort command, string value) => Server.Send(Message.Create(MessageSendMode.reliable, command).AddString(value), clientID);
    public static void Tick() => Server.Tick();
    public static void Stop() => Server.Stop();
    public void Start()
    {
        Instance = this;
        MaxClients = 32;
        RiptideLogger.Initialize(Debug.Log, Debug.Log, Debug.LogWarning, Debug.LogError, false);
        Server = new Server();
        Game.BaseDirectory = AppDomain.CurrentDomain.BaseDirectory;
        if (Game.BaseDirectory == "C:\\Program Files\\Unity\\Hub\\Editor\\2021.3.7f1\\Editor")
        {
            Game.SUPER_DEBUG = Game.DevServer = true;
            Game.LiveOffline = true;
            IP = "127.0.0.1";
            Port = 6000;
        }
        else
        {
            // Blah blah...
        }
        Game.Startup();
        Server.Start(Port, MaxClients);
    }

    [MessageHandler(CCom.Login)]
    public static void Login(ushort fromClientID, Message message)
    {
        string name = message.GetString();
        string error = Database.ValidatePlayer(name, message.GetString());
        if (error == "")
        {
            Player p = Player.Get(name, "");
            if (p == null)
                Send(fromClientID, SCom.LoginError, "Player banned.");
            else
                p.SignIn(fromClientID);
        }
        else
            Send(fromClientID, SCom.LoginError, error);
    }
}`

**Comment by PathPDX** [comment]
Ok, I've decided to go with .Net.Sockets because I need to be able to send large byte arrays using a buffer and AsyncCallback. I'm then deserializing to an object array that I can send straight to a function with reflection.

**Comment by tom-weiland** [comment]
@PathPDX why did you close this? Did you resolve the issue? If so, how? Does this need to be addressed in Riptide's codebase anywhere?
