### ISSUE TITLE
No handler method error despite handler being defined.

### ISSUE THREAD

**Issue by LemMem** [tom-weiland/RiptideNetworking#69]
In my project, I have 2 packets being sent between the server and client simply to share some information about the state of the game. Both the packets are being sent, and on the server side the packet is being handled (the same error does not occur, and I have Log statements during the handler that are being sent). However, on the client side, all I'm getting is this error message:
`No client-side handler method found for message ID 2!`
It's worth mentioning that I have the server logic *and* the client logic defined in the same unity project, switching between them by using the "Server Build" functionality in Unity's build settings. I have both the Server-Side and Client-Side Packet Handlers in one script however in early versions they were both in the client and server scripts respectively and it was still broken. Here is the code;
```c#
using System.Collections;
using UnityEngine;
using RiptideNetworking;

public class PacketHandlers : MonoBehaviour
{
    [MessageHandler((ushort)NetworkCommons.PacketType.SendingClientInfo)] //PacketType.SendingClientInfo is 1
    private static void RecieveClientInfo(ushort fromClientId, Message message)
    {
       //Logic
    }

    [MessageHandler((ushort)NetworkCommons.PacketType.RecievingServerInfo)] //PacketType.RecievingServerInfo is 2
    private static void ReceivingServerInfo(ushort fromClientId, Message message)
    {
        //Logic
    }
}

```
I am aware that [this error has been brought up before](https://github.com/tom-weiland/RiptideNetworking/issues/62) but no actual solution was came to in that thread, so hopefully we can come up with a public solution to this error to kill it once and for all.

**Comment by tom-weiland** [comment]
The error message is correct—you don't have a *client-side* handler method for message ID 2. Your `ReceivingServerInfo` method is a *server-side* message handler. Server-side handlers take two parameters (a `ushort` and a `Message`) while client-side handlers only take one parameter (a `Message`).

**Comment by LemMem** [comment]
This is what i get for not reading the docs thoroughly enough lol, thanks
